"""Add response fields to idempotency requests

Revision ID: 33e74c63193a
Revises: fa65daf3b93a
Create Date: 2026-09-19 16:16:36.155580

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33e74c63193a'
down_revision: Union[str, Sequence[str], None] = 'fa65daf3b93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idempotency_requests', sa.Column('response_status', sa.Integer(), nullable=True))
    op.add_column('idempotency_requests', sa.Column('error_detail', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('idempotency_requests', 'error_detail')
    op.drop_column('idempotency_requests', 'response_status')
    # ### end Alembic commands ###
