"""add outbox retry fields

Revision ID: ac070483319d
Revises: eb4653b4945f
Create Date: 2026-09-20 18:56:23.939579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ac070483319d'
down_revision: Union[str, Sequence[str], None] = 'eb4653b4945f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('outbox_events', sa.Column('attempt_count', sa.Integer(), server_default='0', nullable=False))
    op.add_column('outbox_events', sa.Column('last_error', sa.String(), nullable=True))
    op.add_column('outbox_events', sa.Column('failed_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_outbox_events_unprocessed_created_at'), table_name='outbox_events', postgresql_where='(processed_at IS NULL)')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_outbox_events_unprocessed_created_at'), 'outbox_events', ['created_at'], unique=False, postgresql_where='(processed_at IS NULL)')
    op.drop_column('outbox_events', 'failed_at')
    op.drop_column('outbox_events', 'last_error')
    op.drop_column('outbox_events', 'attempt_count')
    # ### end Alembic commands ###
