permissions:
  contents: read
  packages: write

name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:

  linting-check:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install  dependencies
        run:  pip install -r requirements.txt

      - name: Run ruff
        run: ruff check .

      - name: Check formatting
        run: ruff format --check .


  docker-build:
    runs-on: ubuntu-latest

    needs:
      - linting-check
      - unit-tests
      - integration-tests

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Build Docker Image
        run: | 
          docker build \
          -t booking-backend:${{ github.sha }} \
          ./backend
      - name: Login to GHCR
        if: github.event_name=='push' && github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker tag booking-backend:${{ github.sha }} ghcr.io/angelosgkiose/booking-backend:${{ github.sha }}
          docker tag booking-backend:${{ github.sha }} ghcr.io/angelosgkiose/booking-backend:latest

      - name: Push Docker Image
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        run: |
          docker push ghcr.io/angelosgkiose/booking-backend:${{ github.sha }}
          docker push ghcr.io/angelosgkiose/booking-backend:latest

  unit-tests:
    runs-on: ubuntu-latest

    env:
      DATABASE_URL: postgresql+psycopg://testuser:testpassword@localhost:5432/booking_test
      SECRET_KEY: test-secret-key
      ALGORITHM: HS256
      EXPIRATION_TIME: 30
      REFRESH_TOKEN_EXPIRATION_DAYS: 7
      REDIS_HOST: localhost
      REDIS_PORT: 6379

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run unit tests
        run: python -m pytest tests/unit
  integration-tests:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:17
        env:
          POSTGRES_USER: testuser
          POSTGRES_PASSWORD: testpassword
          POSTGRES_DB: booking_test
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U testuser -d booking_test"
          --health-interval 5s
          --health-timeout 5s
          --health-retries 5

      redis:
        image: redis:7
        ports:
          - 6379:6379
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 5s
          --health-timeout 3s
          --health-retries 5

    env:
      DATABASE_URL: postgresql+psycopg://testuser:testpassword@localhost:5432/booking_test
      SECRET_KEY: test-secret-key
      ALGORITHM: HS256
      EXPIRATION_TIME: 30
      REFRESH_TOKEN_EXPIRATION_DAYS: 7
      REDIS_HOST: localhost
      REDIS_PORT: 6379

    defaults:
      run:
        working-directory: ./backend

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.14"

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run migrations
        run: alembic upgrade head

      - name: Run tests with coverage
        run: python -m pytest tests --cov=app --cov-report=term-missing --cov-fail-under=75